#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check
    methods:  [POST]

api:
    prefix: /api
    resource: '../src/Controller/Rest'